### ISSUE TITLE
podcast:value is allowed in multiple channel elements

### ISSUE THREAD

**Issue by jamescridland** [skymethod/livewire-validator#1]
If you [try to validate this feed](https://validator.livewire.io/?validate=https://podnews.net/rss) then the validator kicks an error:

```
Multiple channel <podcast:value> elements are not allowed[[podcastindex]](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#value)
```

The `podcast:value tag` is now allowed multiple times, to allow for access to multiple payment methods.

I've submitted a pull request to the documentation on Podcast Index, at https://github.com/Podcastindex-org/podcast-namespace/pull/431

The line at https://github.com/skymethod/livewire-validator/blob/97875a2128a8346c6474be6ac0af0de34260c064/validator-worker/static/app.js#L2880 is the one that checks for single elements, and should probably be deleted.

**Comment by johnspurlock-skymethod** [comment]
This was implemented back in 132f302f17396a5dc2e2f2d4eacca5ac547d6b25 once it was added to the namespace!
