### ISSUE TITLE
podcast:location geo check false positive

### ISSUE THREAD

**Issue by Marzal** [skymethod/livewire-validator#2]
![imagen](https://github.com/skymethod/livewire-validator/assets/2069735/39bfd242-5fbb-4bdb-94bb-0f181238bcda)

RegEx is not my sauce but thanks to the debugger in https://regex101.com/ I think that `^geo:-?\d{1,2}(\.\d+)?,-?\d{1,3}(\.\d+)?$` from https://github.com/skymethod/livewire-validator/blob/9446330472ee326baf36c25185ce8ea696f56ff7/validator-worker/common/validation_functions.ts#L75C13-L75C54 is to strict and doesn't allow the `uncertainty` or the `crs` optional parameters.

Sorry for not been able right now to do a MR. And thanks for this great validator.

**Comment by johnspurlock-skymethod** [comment]
Thanks for pointing me to that spec - I just enhanced the regex to follow the ABNF in there for full compliance, and added some positive and negative unit tests.  Go ahead and add to any inputs in the `good` or `bad` lists in the new test.

https://github.com/skymethod/livewire-validator/commit/9ee5bb2c2282a2c66614dc3248bf0950e565d217

Deployed in the production validator as of v0.9.9:
https://validator.livewire.io/?validate=https://kdeexpress.gitlab.io/feed_mp3
