### ISSUE TITLE
podcast:soundbite not counted in Found ...

### ISSUE THREAD

**Issue by Marzal** [skymethod/livewire-validator#4]
`podcast:soundbite` is highlighted but is not counted in Found ...
`Found one podcast namespace tag: <podcast:locked>`

Not sure if this is the wanted behavior, but just in case here are some example feeds:
https://feeds.libsyn.com/45546/rss
https://feeds.buzzsprout.com/1538779.rss

**Comment by mikeneumann** [comment]
This seems to be fixed now?

**Comment by Marzal** [comment]
It's fixed for https://feeds.buzzsprout.com/1538779.rss, thanks.

https://feeds.libsyn.com/45546/rss doesn't use soundbite right now, so not way of testing.
